site_name: "Ler's Sandbox"
site_url: https://cassmastern.github.io/cass-sandbox/
docs_dir: docs

hooks:
  - hooks/accessibility-injector.py

theme:
  name: material
  logo: img/logo.svg
  favicon: img/favicon.ico
  features:
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.select
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

plugins:
  - awesome-pages
  - search
  - open-in-new-tab
  - mermaid2:
      javascript: js/mermaid.min.js
  - plantuml:
      puml_url: http://192.168.1.5:8080
      #puml_url: https://www.plantuml.com/plantuml/svg
  - swagger-ui-tag:
      extra_css:
        - css/swagger-custom.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

          
  - mkdocs_graphviz:
      node_color: "777777"
      node_fontcolor: "777777"
      edge_color: "777777"
      edge_fontcolor: "777777"
      bgcolor: "none"

extra_javascript:
  - js/diagram-utils.js
  - js/seamaiden.js
  - js/diagram-theme-switcher.js
  - js/diagram-zoom.js


extra_css:
  - css/alphabet.css
  - css/diagram-zoom.css
  - css/cm-logo.css
  - css/color-vars.css
  
extra:
  generator: false
  analytics:
    provider: google
    property: G-GD2XWDMP2E
  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
